### ISSUE TITLE
Laravel Passport

### ISSUE THREAD

**Issue by luckys383** [laravelpb/topics#4]
**Laravel Passport**

**Brief description about the content to be covered**

1. Use of Laravel Passport
1. Password Grant Token
1. Protect Routes

**Prerequisites & reading material (Distributed before the session)** 

1. Understanding of Laravel Basics
1. Basic Understanding of OAuth 2.0

**Time required for the talk**
50-60 minutes

**About Myself**
I have around 8 Years of working experience in IT. And working as Team Leader in Logiciel Solutions Pvt. Ltd.

https://www.linkedin.com/in/luckys383
https://twitter.com/luckys383

**Comment by laravelpb** [comment]
Duplicated!
